// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectFinal.Models;

namespace ProjectFinal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectFinal.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Quần"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Áo"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Giày"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Phụ kiện"
                        });
                });

            modelBuilder.Entity("ProjectFinal.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Despition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Color = "Trắng",
                            Count = 3,
                            Despition = "Sơ mi được nhập khẩu từ Cambodia",
                            Name = "Sơ Mi",
                            Price = 35.399999999999999
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Color = "Xám",
                            Count = 2,
                            Despition = "Jeans được nhập khẩu từ Laos",
                            Name = "Jeans rách",
                            Price = 50.5
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            Color = "Nâu",
                            Count = 5,
                            Despition = "Kính được nhập khẩu từ Brunei",
                            Name = "Kính râm",
                            Price = 65.400000000000006
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Color = "Xanh",
                            Count = 3,
                            Despition = "Giày được nhập khẩu từ Lào Cai",
                            Name = "Giày vans",
                            Price = 65.400000000000006
                        });
                });

            modelBuilder.Entity("ProjectFinal.Models.Product", b =>
                {
                    b.HasOne("ProjectFinal.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
